### ISSUE TITLE
Bug method addManyToOneRealtion in migration add a ManyToMany instead

### ISSUE THREAD

**Issue by AdriwanKenoby** [oroinc/crm#231]
Hi Oro Team,

I have extend the task bundle with migration like it describe in this [link](https://www.orocrm.com/forums/topic/extend-task-bundle-using-migration-throw-error-when-try-to-create-task).

The method addManyToOneRelation seems to not work properly.

**Comment by mkudelya** [comment]
Hi @AdriwanKenoby 

I confirmed this bug. It will be fixed as soon as possible.
