### ISSUE TITLE
Error when importing 01/01/1970 as date value

### ISSUE THREAD

**Issue by roldan** [oroinc/crm#234]
Hi, I'm getting this eror when trying to import Contacts via UI using 01/01/1970 as a birthday value. Maybe this is a bug on ImportExportBundle? Any other date works fine.

![screenshot from 2016-12-28 13-09-31](https://cloud.githubusercontent.com/assets/695904/21526001/da7fed44-ccff-11e6-8e86-05b7c88e07dc.png)

Thanks!

**Comment by mkudelya** [comment]
Hi @roldan 

I confirmed the bug. We will fix it as soon as possible.
Thank you!

**Comment by anyt** [comment]
The bug already fixed. Thank you for your contribution!
