### ISSUE TITLE
Disqualify leads in bulk

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#235]
Hello Oro Team,

A smal feature proposal that could be helpfull for many people.  It would be great to be able to `Disqualify` leads in bulk directly from the datagrid.

Have a good day,
Samuel

**Comment by mbessolov** [comment]
Hi Samuel,

It will be possible to do once workflow transitions become available as mass actions in datagrids. Which is on the roadmap, but will be crafted very slowly and carefully not to affecte the datagrids performance. 

Thank you,
Michael
