### ISSUE TITLE
Display Opportunities on the Contact page

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#240]
Hi,

In OroCRM 2.0,  when viewing a Contact information, why does the Opportunities related to the contact are not listed ?

I think there is a link missing.

# Opportunity page 
You can see links to Account and Contact 

![image](https://cloud.githubusercontent.com/assets/794449/22413233/12dd391a-e684-11e6-87b5-232b5536d836.png)

# Account page
Opportunities are listed
![image](https://cloud.githubusercontent.com/assets/794449/22413238/297d8206-e684-11e6-9bb9-810f8df9a97a.png)

# Contact  
Opportunities not listed.

**Comment by artml** [comment]
@sadortun Hi Samuel, thanks for the suggestion!

I agree, there is no obvious reason to this omission, and most likely we just cut this story at some point of development back in 1.0 days and never considered it to be enough priority to finally make it done.

I will put it to our backlog, and since the fix appears quick, will try to push the implementation into one of our nearest releases.

**Comment by sadortun** [comment]
Great meeting thanks !

**Comment by sadortun** [comment]
@artml, would you be able to contaCT me by email, I would like to know more about your Technology partner program. We will continue during the next year's to do contributions to Oro repositories, and we would like to more informations from your roadmap,  and how we collaborate more together. 

Thanks
Samuel

**Comment by mbessolov** [comment]
@sadortun you can simply submit the "Become a partner" form at https://www.orocrm.com/partners - it will get routed to the appropriate team (after all, we are using OroCRM internally to handle all partner inquiries :-) )

**Comment by sadortun** [comment]
@mbessolov ok, will do. I think I've submitted it a few months ago and did not get a response...

**Comment by sadortun** [comment]
@artml @mbessolov We have an implementation for this. PR will follow next week!
