### ISSUE TITLE
Custom fields in email campaign

### ISSUE THREAD

**Issue by wimg** [oroinc/crm#257]
Would it be realistic to have custom fields in an e-mail campaign ?

These fields wuld have to be filled when sending the campaign.

The idea is that one of our customers has to regularly send out notifications of maintenance to equipment. They would like to use the same template, but just fill the dates and times on which the maintenance will occur.

**Comment by mkudelya** [comment]
Hi @wimg 

> Would it be realistic to have custom fields in an e-mail campaign ?

Could you please clarify if are we talking about custom entity fields? Yes, you can add them to email templates.

> The idea is that one of our customers has to regularly send out notifications of maintenance to equipment. They would like to use the same template, but just fill the dates and times on which the maintenance will occur.

Also you can use the [date](https://twig.sensiolabs.org/doc/2.x/functions/date.html) function, for example `{{ date('m d Y') }}`

**Comment by wimg** [comment]
The idea would be that they would send out something like this :

> Dear customer,
We will be performing maintenance on May 5th between 10:00am and 11:00am
Kind regards

The date and time will always be different, so it would be ideal if these could be entered when creating the campaign.

**Comment by sadortun** [comment]
Good idea,

I think a workflow-like popup that ask for specofic fields to be filled when pressing send could be a way to implement this.

**Comment by wimg** [comment]
That sounds like a perfect way of doing this without the need to have fields on the actual campaign form. If the system could read the template and detect any variables in there and ask for those...

**Comment by sadortun** [comment]
Example syntax with filters  that could be possible : 
```
{{ entity.myField | oro_prompt }}
{{ entity.myDate | oro_prompt  }}
```
Let's hope someone is interested in submitting a PR !

**Comment by wimg** [comment]
I'd be willing to give it a go, but I would need a few pointers ;-)

**Comment by mkudelya** [comment]
Also, have a look at the [oro:maintenance-notification](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/NotificationBundle/readme.md)  command, it will be useful in case of customization

**Comment by vbyndych** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
