### ISSUE TITLE
Marketing campaign for "offline" activities

### ISSUE THREAD

**Issue by tomferreira** [oroinc/crm#258]
Control of marketing campaigns works well for online campaigns, but there is a need to manage marketing campaigns "offline" too

To do this, system need to allow associating these campaigns with the activities, such as calls, individual emails, events, meetings, etc.

And system also need to manage these campaign activities the same way that do campaign events

Best regards

**Comment by artml** [comment]
@tomferreira not sure what you mean here. Do you want to enable activities for marketing campaigns? It can be easily done via entity config.

**Comment by vbyndych** [comment]
I am now closing this issue as, unfortunately, we have not received any feedback from you. Please, feel free to reopen it if you have any questions.
