### ISSUE TITLE
Creating reports using 'Lifetime Sales Value' field, returns "invalid query"

### ISSUE THREAD

**Issue by rodolfobandeira** [oroinc/crm#259]
It's not possible to generate reports using the "Lifetime Sales Value" field from Accounts. 
It shows `Invalid query`

The following screenshot is from http://demo.orocrm.com 

[![Screenshot from 2017-03-28 21-32-12.png](https://s17.postimg.org/svoer0h6n/Screenshot_from_2017-03-28_21-32-12.png)](https://postimg.org/image/vprk4gjcr/)

**Comment by mkudelya** [comment]
Hi @rodolfobandeira 

Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.

**Comment by mkudelya** [comment]
Internal task BAP-14500

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/crm/commit/4ff7c36b134cd8a1da34a25438eeeba6f444fda8.

Thank you for contribution!
