### ISSUE TITLE
Unable to export opportunities

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#267]
When exporting opportunities, the export is not succesfull,  ` Export operation failed, 1 error(s) found. Error log`

```
An unexpected value could not be normalized: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency::__set_state(array(
   'value' => NULL,
   'baseCurrencyValue' => NULL,
   'currency' => 'USD',
))
```

 and the following is logged :
```
batch.ERROR: Encountered an error executing the step: An unexpected value could not be normalized: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency::__set_state(array(    'value' => NULL,    baseCurrencyValue' => NULL,    'currency' => 'USD', )) [] []
```

**Comment by mkudelya** [comment]
Hi @sadortun 

As usual i want to ask you:

- Did you customize the opportunity entity?
- What version of orocrm do you use?

I have tested on v2.1 but I have no problems with the opportunity export. The error happens [here](https://github.com/orocrm/platform/blob/2.1.1/src/Oro/Bundle/ImportExportBundle/Serializer/Serializer.php#L46), but during my debug the $data variable was never equal to the 'Oro\Bundle\CurrencyBundle\Entity\MultiCurrency' object.

**Comment by sadortun** [comment]
Hi @mkudelya,

Indded, sorry about the missing info ! 
> Did you customize the opportunity entity?
No. 
We use $CAD as a currency.

> What version of orocrm do you use?
2.1

**Comment by mkudelya** [comment]
Hi

Unfortunately i can't reproduce this issue. It would be nice if you could write the steps to reproduce this on a new installation.

**Comment by sadortun** [comment]
Sure, I'll give it a try on a fresh ibstall.

**Comment by manowark** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
