### ISSUE TITLE
Opportunity without Accounts ?

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#271]
Hi @artml,

We have in some cases, customers who are self employed that do not have distinct compagny. Do you think it would be valuable to be able to create Opportunities related to a Contact, without being associated to an Account ?  

Why does the Opportunity Account field is mandatory ? 

Thanks,
Samuel

**Comment by artml** [comment]
@sadortun I don't think it should be valuable to be honest. Let me explain why.

In our system Account is the primary entity to represent the customer and track all customer interactions—communication, sales, complaints, anything. Account may represent any type of customer, be it a company or individual or whatever else.

On the contrary, contacts are used to merely store some contact information such as emails or addresses and are not supposed to track sales or any customer interactions other than communication. They _can_ be related to an opportunity but just as a convenience.

Hence we require the opportunity or any other sales entity to be associated with Account and, if necessary, a specific Customer record. This requirement stems from the necessity to have a single point of reference to all customer interactions that is Account, not Contact.

In your case I'd suggest to create an account record for this individual customer in the same way you create account records for companies. Name it after the person, relate it to the contact, and work with it as you work with other accounts.

Hope this helps.

**Comment by sadortun** [comment]
Thanks you.
