### ISSUE TITLE
Call entity data contains html markup in reporting

### ISSUE THREAD

**Issue by jbeaver117** [oroinc/crm#281]
Running reports based on the Call entity will display html markup for the Call entity based data. 

This is recreatable by creating a custom report based on the Call entity that contains fields such as the Calls/Additional Comments field. The HTML markup is not sanitized prior to save to the database, and will display on any/all reports run with this data.

**Comment by alexandr-parkhomenko** [comment]
Hi @jbeaver117,

There is limited list of html tags and attributes that we allow to save in database within comment. All unexpected tags and attributes truncates from comment message before keep to database.

**Comment by manowark** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
