### ISSUE TITLE
Tags are not available on *.csv import

### ISSUE THREAD

**Issue by vtsykun** [oroinc/crm#284]
I found very strange code in OroCRM - the tag Import/export was broken by the listener in OpportunityBundle. https://github.com/oroinc/crm/blob/d67d764e3df3a02528d95855f43b20338332b7a6/src/Oro/Bundle/SalesBundle/Resources/config/services.yml#L637-L640
if I will disable listener then tags import works fine

**Comment by manowark** [comment]
Hi, @vtsykun. Thank you for reporting an issue.

It seems like a bug. Service with name `oro_tag.event_listener.import_export_tags_subscriber` present in `TagBundle` too. So, Disabling service in `SalesBundle` restore functionality of original listeners. I'll recheck that in short time and will create a bug to our backlog.

**Comment by manowark** [comment]
Bug crated, INTERNAL ID: CRM-8469

**Comment by mbessolov** [comment]
This issue was fixed, the fix will appear in the master branch shortly and will be included in the next release.
