### ISSUE TITLE
Very slow query for emails

### ISSUE THREAD

**Issue by jneto81** [oroinc/crm#286]
Hello, a have  very slow query for emails. ( 28 seconds for me )
Oro version 2.4
oro_email:  12608
oro_email_address: 1657
oro_email_folder: 47
oro_email_user: 12608
oro_email_origin: 1

SELECT COUNT(*) FROM (SELECT o0_.id AS id_0 FROM oro_email_user o0_ LEFT JOIN oro_email o1_ ON o0_.email_id = o1_.id LEFT JOIN oro_email_user_folders o3_ ON o0_.id = o3_.email_user_id LEFT JOIN oro_email_folder o2_ ON o2_.id = o3_.folder_id LEFT JOIN oro_email_origin o4_ ON o2_.origin_id = o4_.id AND o4_.name IN ('emailorigin', 'internalemailorigin', 'useremailorigin') WHERE o4_.isActive = 1 AND ((o0_.id IN (SELECT MAX(o5_.id) AS dctrn__1 FROM oro_email_user o5_ INNER JOIN oro_email o6_ ON (o5_.email_id = o6_.id) WHERE o6_.thread_id IS NOT NULL AND (o5_.user_owner_id = 1 AND o5_.organization_id = 1) GROUP BY o6_.thread_id)) OR (o1_.thread_id IS NULL AND o1_.is_head = 1)) AND (o0_.user_owner_id = 1 AND o0_.organization_id = 1) GROUP BY o0_.id) AS e;
--

**Comment by getron-pl** [comment]
I know that we had a case with around 20k emails working on MySQL and it is possible to get good response time for emails grid. Please, try to adjust your MySQL settings:

* increase join_buffer_size
* increase key_buffer_size
* increase sort_buffer_size
* increase innodb_buffer_pool_size
* increase innodb_log_buffer_size

according to the resources available on your server.

**Comment by jneto81** [comment]
Thanks. 
I did try in another machine with a different setup and get 160 ms.  I have to research more the mysql optimizations.

Any more recommendations for mysql ?
