### ISSUE TITLE
"An Exception was thrown while handling: Internal Server Error" when trying to access Oro

### ISSUE THREAD

**Issue by martinvonwittich** [oroinc/crm#295]
I had our OroCRM testing instance shutdown yesterday because of #292 (I was afraid it might fill up its hard disk). Today I've booted it again, but now I'm unable to open the website - it just displays:

```
An Exception was thrown while handling: Internal Server Error
```

`app/logs/prod.log` logs:

> [2017-12-06 15:14:56] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Oro\Bundle\DashboardBundle\Model\Manager::findUserActiveOrDefaultDashboard() must be an instance of Oro\Bundle\UserBundle\Entity\User, null given, called in /var/www/crm-application/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Controller/DashboardController.php on line 311" at /var/www/crm-application/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/Manager.php line 215 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Oro\\Bundle\\DashboardBundle\\Model\\Manager::findUserActiveOrDefaultDashboard() must be an instance of Oro\\Bundle\\UserBundle\\Entity\\User, null given, called in /var/www/crm-application/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Controller/DashboardController.php on line 311 at /var/www/crm-application/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/Manager.php:215)"} []

I don't know what exactly triggered this error, but I believe it might have something to do with an old session and the cookies in my browser, because it works fine when I access it in an incognito window and just log in normally.

**Comment by manowark** [comment]
Hello, @martinvonwittich.

Has there been any code customization done?
Please try to clear cookies for that website and try to re-login. Then let me know the result.

**Comment by martinvonwittich** [comment]
> Has there been any code customization done?

Nope, not as far as I know of. `git` seems to confirm this, at least if I'm using it right ^^

```
orocrm.iserv.eu /var/www/orocrm # LC_ALL=C git status -u all
On branch 2.5
Your branch is up-to-date with 'origin/2.5'.
nothing to commit, working tree clean
```

> Please try to clear cookies for that website and try to re-login. Then let me know the result.

Yes, clearing the cookies solved this problem. I'd still argue though that OroCRM should catch this exception and e.g. try to clear the cookies itself, or redirect to the login page instead of just crashing.

**Comment by manowark** [comment]
First we need to understand how to reproduce that problem. Then we will have idea how to fix it.
Could you please help me with steps to reproduce that issue?

**Comment by martinvonwittich** [comment]
> First we need to understand how to reproduce that problem. Then we will have idea how to fix it.
> Could you please help me with steps to reproduce that issue?

Sorry, no idea :(
I tried to reboot the VM again, but that didn't cause the issue again. I also tried `cache:clear` (did that a lot while trying to debug our message consumer issues), but that didn't break it either. Feel free to close this issue until I or someone else encounters this again.

**Comment by manowark** [comment]
I'm now closing this issue. Please, feel free to reopen it if you have any questions.

**Comment by Ashish539** [comment]
I am unable to open the orocrm application.i am trying to add product bundle to orocrm
what is the solution for this error 
An Exception was thrown while handling: Internal Server Error

created a product bundle then onwards getting this error . i removed the bundle  then also getting the same error anybody have the exact solution for this error

**Comment by kkrieger85** [comment]
I also face this problem. 

Fresh installation without modification. Installed via `composer create-project oro/commerce-crm-application oroapp --repository=https://satis.oroinc.com`

Current Version 3.1.6

var/log/prod.log
```
[2019-04-26 17:13:09] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Oro\Bundle\DashboardBundle\Model\Manager::findUserActiveOrDefaultDashboar
d() must be an instance of Oro\Bundle\UserBundle\Entity\User, null given, called in /var/www/share/oroapp-3.1.6/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Controller/Dashboa
rdController.php on line 313" at /var/www/share/oroapp-3.1.6/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/Manager.php line 213 {"exception":"[object] (Symfony\\Component
\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Oro\\Bundle\\DashboardBundle\\Model\\Manager::findUserActiveOrDefaultDashboard() must be an instance of Oro\\Bundle\\UserBundle\\Entity\\User,
 null given, called in /var/www/share/oroapp-3.1.6/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Controller/DashboardController.php on line 313 at /var/www/share/orocommerce-pr
oject-mde/production/releases/oroapp-3.1.6/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/Manager.php:213)"} []
```

**Comment by anyt** [comment]
Hi @kkrieger85,
Please share the environment configuration details, the list of commands you have used to install an application and what are you doing after an installation.
I've just checked it locally, installed with the same command, Current Version 3.1.6, no issues, prod.log is empty.

**Comment by anyt** [comment]
Also, make sure the installation is really clean, it's recommended to remove and create an empty database, clear the `var/cache/` folder and set the `installed` flag to `false` in `config/parameters.yml` file.

**Comment by kkrieger85** [comment]
I just cleared `var/cache/{prod/dev}`
I set `installed`to `false`
and reinstalled it with command `php ./bin/console oro:install --env=prod --timeout=900  --drop-database`

Isssue still occurs

**Comment by kkrieger85** [comment]
I solved my issue with escaping strings in yml. 

If you go through installation after composer install, the entered strings like DB-password, web_backend_prefix are stored as unescaped strings in parameters.yml

Also web_backend_prefix is stored without trailing `/`
