### ISSUE TITLE
How to pass additional query parameters to ImportExport Button?

### ISSUE THREAD

**Issue by kusgpt26** [oroinc/crm#298]
Hi,
I have an installation of orocrm2.0.
I have created an entity named **ContactStatus** which is connected to **Opportunity**. I also created datagrid for ContactStatus that is showed in Opportunity view page based on opportunity id. Here is code-

`{% set executiveDataRender %}`
    `<div class="contact-widget-wrapper" >`
    `<div class="box-type1" style="background:transparent;">`
      `{% if entity.contactStatus is not empty %}`
        `{{ dataGrid.renderGrid('contact-status-grid', {opportunityId: entity.id}) }}`
      `{% else %}`
        `<div class="no-data">`
          `<span>No data found</span>`
        `</div>`
      `{% endif %}`
    `</div>`
  `</div>`
`{% endset %}`

I also created **export system** for this ContactStatus on opportunity view page. Here is code-

`{% set executiveDataRender %}`
  `<div class="contact-widget-wrapper" >`
	`{% include 'OroImportExportBundle:ImportExport:buttons.html.twig' with {`
	    `entity_class: entity_class,`
	    `exportProcessor: 'demo_contact_contact_status_export',`
	    `exportTemplateProcessor: 'demo_contact_contact_status_export_template',`
	    `dataGridName: 'contact-status-grid'`
	`} %}`
    `<div class="box-type1" style="background:transparent;">`
     ` {% if entity.contactStatus is not empty %}`
       ` {{ dataGrid.renderGrid('contact-status-grid', {opportunityId: entity.id}) }}`
     ` {% else %}`
        `<div class="no-data">`
          `<span>No data found</span>`
        `</div>`
      `{% endif %}`
    `</div>`
  `</div>`
`{% endset %}`

It is working properly and export entire data of **ContactStatus** which is correct according to what i have written.
But i want to export only selected data which is shown in datagrid (contact-status-grid) according to opportunty id.
Is there any way to pass additional query parameters (like here i want to pass OpportunityId )in ImportExport Button so that it only export filtered records?

**Comment by aalgogiver** [comment]
Hi, you need to use [grid export functionality](https://github.com/oroinc/platform/blob/2.6/src/Oro/Bundle/DataGridBundle/Resources/doc/backend/extensions/export.md).
