### ISSUE TITLE
create marketing List throw FatalThrowableError in DictionaryFilter.php line 91

### ISSUE THREAD

**Issue by AdriwanKenoby** [oroinc/crm#301]
Call to a member function getJoin() on boolean when I attempt to create a marketing List.

However the marketingList is created and displayed on grid.

Fresh install of orocommerce 1.6.

**Comment by vladimirseniuk** [comment]
Hello, @AdriwanKenoby

Thank you for submitting the issue. Internal ID: BAP-16617

**Comment by AdriwanKenoby** [comment]
Same problem on EmailCampaign, when the entity was created, oro try to redirect user to a view page, call the function getJoin() and fail.

**Comment by aivus** [comment]
Hi @AdriwanKenoby 

This bug was fixed. The fix will appear in the master branch shortly, and will be included in the next release.
