### ISSUE TITLE
Installer does not report php7.1 requirement

### ISSUE THREAD

**Issue by mrbig** [oroinc/crm#302]
Tried to install oroCRM from commit 5b53363.

The installer.php reported everything ok, except a few warnings, but the next button remained disabled.

When looking into to code, and dumping out the $majorProblems variable, we found there is a "hidden" requirement, that is not displayed among the requirements list:

array(1) {
  [0]=>
  object(OroRequirement)#21 (5) {
    ["fulfilled":"Requirement":private]=>
    bool(false)
    ["testMessage":"Requirement":private]=>
    string(60) "PHP version must be at least 7.1 (5.6.33-0+deb8u1 installed)"
    ["helpText":"Requirement":private]=>
    string(63) "Install PHP 7.1 or newer (installed version is 5.6.33-0+deb8u1)"
    ["helpHtml":"Requirement":private]=>
    string(203) "You are running PHP version "<strong>5.6.33-0+deb8u1</strong>", but Oro needs at least PHP "<strong>7.1</strong>" to run.Before using Oro, upgrade your PHP installation, preferably to the latest version."
    ["optional":"Requirement":private]=>
    bool(false)
  }
}

Please see attached screenshot (it's a pdf, sorry):
[Oro Application installation.pdf](https://github.com/oroinc/crm/files/1739414/Oro.Application.installation.pdf)

Please add this to the mandatory requirements as well

**Comment by vitaliyberdylo** [comment]
Thank you for reporting the issue!
We will fix it as soon as possible.
We greatly appreciate all contributions to Oro projects.

**Comment by anyt** [comment]
Fixed https://github.com/oroinc/crm-application/commit/cbc462ee9ef2cf1f83f781804a0f5d1fbb71eb20

Thank you for contribution!
