### ISSUE TITLE
OroMarketing broken

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#304]
Hi @soloma88

In https://github.com/oroinc/OroCRMMarketingBundle/commit/0124328472fb079d3bf1be4275b387413dc59b43   a call was added to  `parent::isApplicable($config)` but the parent class does not implement the method in oro/platform in branch 2.3, but only on branch `master`

https://github.com/oroinc/platform/blob/2.3/src/Oro/Bundle/DataGridBundle/Extension/AbstractExtension.php

There is a commit missing in platform `2.3`  required by marketing bundle

Thanks,
Samuel

**Comment by mbessolov** [comment]
( tracking ID - CRM-8739 )

**Comment by mbessolov** [comment]
The problem doesn't exist in the latest release. Please upgrade.
