### ISSUE TITLE
'firstName' filter is not supported in OroCRM Rest JSON API

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/crm#306]
When I tested the Oro API in `/api/doc/rest_json_api#get--api-contacts` I've tried two filters. The first worked well, that is the field 'lastName' (See the image below):

![certo](https://user-images.githubusercontent.com/10530520/39131493-e5fd6546-46e5-11e8-98cf-8f0b0f9a172e.PNG)

But when I change the filter to be 'firstName' (that Oro has a default field from installation), the endpoint not works, giving me an unexpected error (See the image below):

![erro](https://user-images.githubusercontent.com/10530520/39131529-02702d94-46e6-11e8-851a-f6cb0fc12e9a.PNG)

How do I, through the Oro REST API, select all contacts filtering by 'firstName'? Is this a bug?

Thanks!

**Comment by anyt** [comment]
There is documentation in first tab of every methods, and there is no firstName filter described.

But it's strange that this filter was not enabled by default I don't see any configuration responsible for that, let me check.

**Comment by pedrofurtado** [comment]
@anyt Notify us if you have any news about this, or some workaround until the final solution. Thanks!

**Comment by vsoroka** [comment]
Hello @pedrofurtado,
by default the filtering is enabled only for fields which have the database index. It is made by performance reasons.
To enable filtering for "firstName" field you can add DB index for it or [enable it in api.yml](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/configuration.md#filters-configuration-section) if you sure that it is safe for your application.

**Comment by pedrofurtado** [comment]
@vsoroka Could you give me an example code of `api.yml` that enables 'firstName' as a filter in Gold JSON API? Because I do not know in which folder I have to create this file, and neither what content it should have to works.

**Comment by anyt** [comment]
File should be created at `Resources/config/oro` directory at your bundle

**Comment by anyt** [comment]
It's described at the beginning of documentation that @vsoroka mentioned before
https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/configuration.md#overview

**Comment by pedrofurtado** [comment]
@anyt @vsoroka After create this file, I need to execute some command in console to make it works? And I can make it works in a already created Oro Application, right?

**Comment by pedrofurtado** [comment]
@anyt Thank you! I will try to package this issue into a new bundle. I will feedback you later about this. Thanks again!

**Comment by pedrofurtado** [comment]
@anyt @vsoroka I created a micro bundle (https://github.com/pedrofurtado/orocrm-firstname-api-bundle) that has this funcionality out of box.

**Comment by anyt** [comment]
Look like a good example of simple api customization.

I guess the issue can be closed.

**Comment by pedrofurtado** [comment]
@anyt Thanks for feedback! The issue can be closed.

**Comment by sadortun** [comment]
@pedrofurtado  can you share publicly your micro-bundle ? It would be useful to us :) 

Thanks in advance !

**Comment by pedrofurtado** [comment]
@sadortun I upload the bundle to github: https://github.com/pedrofurtado/orocrm-firstname-api-bundle

It is also available for download in Composer 👍
