### ISSUE TITLE
Cannot start Websocket server

### ISSUE THREAD

**Issue by janpekar** [oroinc/crm#310]
After installation of orocrm version 3.0.0-rc I tried to start websocket server, but there are no such console commands..

I tried
  php ./bin/console gos:websocket:server --env=prod 
or (googled another websocket server used)
 php ./bin/console clank:server --env=prod

But response is
 There are no commands defined in the "gos:websocket" namespace.
or 
 There are no commands defined in the "clank" namespace.

Thank you for help

**Comment by Briones** [comment]
Where can I read the documentation about how to chango to this new bundle? I'm upgrading an OroCRM application from 2.3 to 3.0 and I have the same errors:

```
In StreamIO.php line 141:
clank_1           |
clank_1           |   stream_socket_client(): unable to connect to tcp://rabbitmq:5672 (Connectio
clank_1           |   n refused)
clank_1           |
clank_1           |
clank_1           |
clank_1           |
clank_1           |   There are no commands defined in the "clank" namespace.
```

**Comment by anyt** [comment]
The new command is
`/bin/console gos:websocket:server`

This mentioned on an installation guide for 3.0.0 version
https://oroinc.com/oroplatform/doc/current/install-upgrade/installation-quick-start-dev/commerce-crm#configure-the-supervisor
