### ISSUE TITLE
how to add field acl constraint in an entity?

### ISSUE THREAD

**Issue by videni** [oroinc/crm#311]
there is an entity which has a field named `organization`,  one user can see it , but not another , how can I add  field level permission to it ?

**Comment by videni** [comment]
@anyt, I read these links, but I don't know how to do it in my custom entity, is there an example in oro platform source code that I can refer to?

**Comment by anyt** [comment]
`\Oro\Bundle\AccountBundle\Entity\Account` and `\Oro\Bundle\SalesBundle\Entity\Opportunity` entities have field level ACL enabled.

After enabling field level ACL for the entity you can configure access at the Role Edit page, this is already covered in admin guide I referred above.

**Comment by anyt** [comment]
If after configuring you don't see controls for field level ACL at the Role Edit page, go to `System > Entities > Entity Management`, find your entity, go to Edit page and make sure ` Field Level ACL` checkbox marked as `enabled`

**Comment by videni** [comment]
@anyt,  see it,  thank you so much.
