### ISSUE TITLE
API can not handle urlencoded parameters

### ISSUE THREAD

**Issue by theq86** [oroinc/crm#312]
Example:

`http://crm.example.org/api/contacts?filter[primaryEmail]=some.user@forst-test.de`
This works.

However, some http libraries require an http request to really be well-formed. Thus, the correct parameter to send to the server would be

`http://crm.example.org/api/contacts?filter%5BprimaryEmail%5D%3Dsome.user%40forst-test.de`

If the parameters are urlencoded, the filter will not work.

**Comment by vsoroka** [comment]
An internal issue ID to fix: BAP-17463

**Comment by theq86** [comment]
Good evening, I have some more information on that topic.

I got my ApiClient to work when I urlencoded the query param name and value ONLY, not the whole query string.

`http://crm.example.org/api/contacts?filter%5BprimaryEmail%5D=some.user%40forst-test.de`

This has worked even with my pedantic http client implementation.

So this bug is no real show stopper.

**Comment by anyt** [comment]
Fixed in scope of https://github.com/oroinc/platform/commit/7a06ab4205976b4e7f7c41bf4f4a1d4431a399d1.

Thank you for contribution, @theq86 !
