### ISSUE TITLE
API: Wildcard / Regex search ?

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#314]
Hi Oro Team,

Is it possible using the API to filter using either regex or wildcards ?

For example, if you want to search all contacts having the email ending by `@oroinc.com`
> GET /api/orocrmcontacts?filter[primaryEmail]=**%@oroinc.com**

Thanks,
Samuel

**Comment by vsoroka** [comment]
Yes, it is possible, but you have to enable additional operators for filters, please take a look at https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/how_to.md#enable-advanced-operators-for-string-filter

**Comment by sadortun** [comment]
That's awesome ! Thanks @vsoroka
