### ISSUE TITLE
3.1.0-rc Google Maps Blank

### ISSUE THREAD

**Issue by fyrye** [oroinc/crm#321]
**Server:**
oroinc/crm-application: 3.1.0-RC _(fresh installation)_
CentOS 6.10
Apache 2.4 IUS `SSL + PHP-FPM`
PHP 7.2.11 remi

**Steps:**
- Navigated to https://console.cloud.google.com/apis/
- Created new project
- Enabled APIs for project:
  - Geocoding API
  - Gmail API
  - Maps Embed API
  - Maps JavaScript API
  - Maps SDK for Android
  - Maps SDK for iOS
  - Maps Static API
  - Places API for Web
  - Street View Publish API
  - Street View Static API
- Added Credentials for OAuth 2.0  and API key _(currently unrestricted)_
- Logged in to ORO CRM with Administrator credentials
- Navigated to System -> Configuration -> Integrations -> Google Settings
- Entered in Client ID, Client Secret, Google API Key
- Enabled SSO with appropriate domain
- Enabled OAuth 2.0 Email Sync
- Tested Email Sync and SSO - Both worked
- Added new Contact with valid address
- Clicked Save and Close
- Validated Request was received in Geocoding API
- Tested in Firefox and Chrome

**Received:**
On the contact view page; a blank box, with an `iframe src="about:blank"` that contains empty `head` and `body` html elements where the map is expected to be displayed.

No Error Messages were displayed in the browser console other than:
`Google Maps JavaScript API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required`

GeocoderService.Search is retrieving the address details with a `status: "OK"` 

**Expected:**
Google Maps or an Error message to be display in the contact view page or browser console.

**Comment by abdessamad** [comment]
Hi @fyrye ,

The issue is still valid for latest version (3.1.3).

Is there any news about it?

**Comment by fyrye** [comment]
Closing as resolved in v3.1.6
