### ISSUE TITLE
Config check instructs to disable Phar, but it is required for installation

### ISSUE THREAD

**Issue by sundbry** [oroinc/crm#322]
I followed the instructions during the install to disable the Phar extension since it was a warning.

| OK      | Phar extension is disabled

However, the installation failed due to the missing extension:

`Running full re-indexation with "oro:search:reindex" command
Started reindex task for all mapped entities
Reindex finished successfully.

Preparing application.
Processing language "English" ...
PHP Fatal error:  Class 'Phar' not found in /var/www/orocrm/vendor/composer/composer/src/Composer/Factory.php on line 514

In Factory.php line 514:

  Attempted to load class "Phar" from the global namespace.
  Did you forget a "use" statement?

oro:language:update [--language [LANGUAGE]] [--all] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--] <command>

The command '/usr/bin/php7.1' '/var/www/orocrm/bin/console' 'oro:language:update' '--all' '--env=prod' terminated with an exit code: 255.`

**Comment by sundbry** [comment]
```| WARNING | Disable Phar extension to reduce the risk of PHP unserialization vulnerability.```
Was the warning. closing this issue since it should not make a difference after the command succeeds the first time.

**Comment by anyt** [comment]
Hi @sundbry ,
You are right, composer requires this extension, but it's also not recommended to run composer on a production web server. Instead you should prepare all the vendors as a part of deployment on a build server or locally.
Then you could disable Phar extension as it's not required in runtime.

**Comment by anyt** [comment]
The bug with dependency to Phar during installation is already fixed in 3.1 version and the fix will be available in `3.1.0-LTS` release
