### ISSUE TITLE
Snooze tasks

### ISSUE THREAD

**Issue by dhanyaghegde** [oroinc/crm#335]
Really impressed with the feature set OROCRM has to provide. But, I would like to know if we could have a snooze option added to the tasks. What I mean is, if we could have the product alert you at certain time intervals? Maybe as a mail or update on the task itself?

Thank you.

**Comment by mbessolov** [comment]
Thank you for the feedback on OroCRM!
You can use reminders for the same purpose.
Please check https://forum.oroinc.com/orocrm/orocrm-feature-requests/topic/snooze-tasks#post-38871 for the link to the documentation.
