### ISSUE TITLE
OroCRM: Installer fails on ORO SPECIFIC REQUIREMENTS

### ISSUE THREAD

**Issue by alihaider1793** [oroinc/crm#340]
![ORO](https://user-images.githubusercontent.com/33286510/60253105-f9a7cd00-98e4-11e9-82fa-1cd1828cd079.PNG)

I do not have multiple versions of PHP installed in my computer and the path of PHP is defined in the environment variables of the system. How can I resolve this issue?

**Comment by anyt** [comment]
What version of OroCRM you are trying to install?

The Web Installer was deprecated and removed a long time ago.
Please use the last 3.1.8 LTS version and follow the CLI installation guide
https://oroinc.com/orocrm/doc/current/install-upgrade/installation-quick-start-dev/crm#installation-crm-ce-readme

**Comment by anyt** [comment]
If you are using an old version intentionally, make sure the environment variable holds a valid value.

**Comment by alihaider1793** [comment]
I was following the installation instructions from this link:
https://oroinc.com/orocrm/doc/2.0/dev-guide/installation

and I downloaded the source code from the resource-> downloads from the following link:
https://oroinc.com/orocrm/download#source

**Comment by anyt** [comment]
This is documentation for 2.0 version that is not supported anymore. Please use instruction I mentioned before for 3.1 LTS.

**Comment by alihaider1793** [comment]
if i followed the steps mentioned in the installation guide
https://oroinc.com/orocrm/doc/1.12/dev-guide/installation

and clone the repository using the following command, it would still give me the same error
git clone -b 1.10.12 https://github.com/orocrm/crm-application.git orocrm

**Comment by anyt** [comment]
Why do you want to install outdated 1.10.12 version instead of the current 3.1.8?

**Comment by anyt** [comment]
Please check [Understand Release Process](https://oroinc.com/orocrm/doc/current/community/release-process) to see the difference between versions.

**Comment by alihaider1793** [comment]
Okay so I have gone through the instructions for the 3.1.8 LTS version
https://oroinc.com/orocrm/doc/current/install-upgrade/installation-quick-start-dev/crm#installation-crm-ce-readme

I want to install it in my system in which I have:
Windows 10 (installed in SSD)
PHP version 7.1
Composer version 1.8.6
Git version 2.21
NodeJS version 10.16
Apache 2.4 (I don't want to use Nginx v.1.12)

**Comment by anyt** [comment]
it is highly recommended to use Linux or MacOs, however, Windows is also supported for the dev environment.
But you should notice that application works significantly slower on Windows.
