### ISSUE TITLE
[Question] Commands to run after every deploy or CI?

### ISSUE THREAD

**Issue by Briones** [oroinc/crm#342]
I have a crm-application deployed by a CI system, but normally I have to run the commands manually after the deploy depending if I added migrations or not to run the migrations commands, or the `oro:translation:load`, or the `oro:assets:build`, etc... 

My question is, is there a command that can I execute to run all the necessary steps for a normal deploy? Or which commands should be running manually after every deploy and in what order? I tried to search some information in your documentation but without luck.

I noticed that the `oro:platform:update` command could be an option since it internally runs all the migrations, permissions and assets, but I don't know if it's secure to use it after every deploy.

Internally what commands do you run after the deploy or as a step of your CI system?

**Comment by anyt** [comment]
`oro:platform:update` is the right command, but to make it safe, just follow the upgrade guide https://oroinc.com/b2b-ecommerce/doc/current/dev-guide/install-upgrade-and-patch/how-to-upgrade-to-new-version

As it is highly recommended to enable maintenance mode and stop the queue and cron before running the command to don't have any unexpected issues and enable everything again after the command finished successfully.

**Comment by Briones** [comment]
Thanks for the information, maybe in the future you can add that to the documentation or make a wrapper for that command with a more intuitive name like "oro:platform:deploy" or something like that.
