### ISSUE TITLE
API: Filter[primaryEmail] VS Filter [emails] performance

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#348]
Hi Oro Team,

We are having an issue where searching for a contact via the API, when using the `filter[primaryEmail]` the API returns in 300 ms, but when we use `filter[emails]` the filter takes 10 seconds to execute.

![image](https://user-images.githubusercontent.com/794449/69392965-d4f22e80-0ca5-11ea-9440-646a413ac7b0.png)

We also tested direct SQL and the responses are instantaneous
![image](https://user-images.githubusercontent.com/794449/69393054-1387e900-0ca6-11ea-9a28-c7c4047669b4.png)

Even a `contains` query only takes 200ms to execute.

![image](https://user-images.githubusercontent.com/794449/69393093-2dc1c700-0ca6-11ea-921d-ff7117ce4d35.png)

Any idea why the `emails` filter is slow ?

Thanks,
Samuel

**Comment by vsoroka** [comment]
Hi Samuel,

It is very strange because SQL for both filters are very similar.

for `filter[primaryEmail]`:
```sql
SELECT *
FROM orocrm_contact o0_
INNER JOIN orocrm_contact_email o10_ ON o0_.id = o10_.owner_id
LEFT JOIN orocrm_contact_source o1_ ON o0_.source_name = o1_.name
LEFT JOIN orocrm_contact_method o2_ ON o0_.method_name = o2_.name
LEFT JOIN oro_user o3_ ON o0_.user_owner_id = o3_.id
AND (o3_.organization_id = 1)
LEFT JOIN oro_user o4_ ON o0_.assigned_to_user_id = o4_.id
AND (o4_.organization_id = 1)
LEFT JOIN orocrm_contact o5_ ON o0_.reports_to_contact_id = o5_.id
AND (o5_.organization_id = 1)
LEFT JOIN oro_user o6_ ON o0_.created_by_user_id = o6_.id
AND (o6_.organization_id = 1)
LEFT JOIN oro_user o7_ ON o0_.updated_by_user_id = o7_.id
AND (o7_.organization_id = 1)
LEFT JOIN oro_organization o8_ ON o0_.organization_id = o8_.id
LEFT JOIN oro_attachment_file o9_ ON o0_.picture_id = o9_.id
WHERE o10_.email = ?
  AND o10_.is_primary = ?
```

for `filter[emails]`:
```sql
SELECT *
FROM orocrm_contact o0_
INNER JOIN orocrm_contact_email o10_ ON o0_.id = o10_.owner_id
LEFT JOIN orocrm_contact_source o1_ ON o0_.source_name = o1_.name
LEFT JOIN orocrm_contact_method o2_ ON o0_.method_name = o2_.name
LEFT JOIN oro_user o3_ ON o0_.user_owner_id = o3_.id
AND (o3_.organization_id = 1)
LEFT JOIN oro_user o4_ ON o0_.assigned_to_user_id = o4_.id
AND (o4_.organization_id = 1)
LEFT JOIN orocrm_contact o5_ ON o0_.reports_to_contact_id = o5_.id
AND (o5_.organization_id = 1)
LEFT JOIN oro_user o6_ ON o0_.created_by_user_id = o6_.id
AND (o6_.organization_id = 1)
LEFT JOIN oro_user o7_ ON o0_.updated_by_user_id = o7_.id
AND (o7_.organization_id = 1)
LEFT JOIN oro_organization o8_ ON o0_.organization_id = o8_.id
LEFT JOIN oro_attachment_file o9_ ON o0_.picture_id = o9_.id
WHERE o10_.email = ?
```

I suppose that SQL server can build not optimal execution plan due to a lot of `LEFT JOIN`s.
To quick check whether the issue is related to the joins or not, you can try to use `fields[contacts]` filter to reduce the number of joins. If it will help, you need to investigate the execution plan for the slow SQL query.

**Comment by sadortun** [comment]
Hi @vsoroka 

I ran some more tests, and i've found that it one of our config file that added the `case-sensitive: false` option which added `LOWER` in the where clause.

![image](https://user-images.githubusercontent.com/794449/69502139-c8eeb280-0ed9-11ea-99a1-7d365994b8b1.png)

Thanks for your help,
Samuel
