### ISSUE TITLE
Upgrade from version 3.1 to version 4.2

### ISSUE THREAD

**Issue by simoncarre** [oroinc/crm#365]
**Summary**  
I'm trying to update a local project from version 3.1 to version 4.2. I updated the docker container to match all the requirements (cf. https://doc.oroinc.com/backend/setup/system-requirements/)

**Steps to reproduce**  
After following this guide: https://doc.oroinc.com/backend/setup/upgrade-to-new-version/. I launched the command `php bin/console oro:platform:update --env=dev --force`

**Actual Result**
```
Check system requirements
+---------+--------------------------------------------------------------------------------------------------------+
| Check   | Optional recommendations                                                                               |
+---------+--------------------------------------------------------------------------------------------------------+
| WARNING | To get the latest internationalization data upgrade the ICU system package and the intl PHP extension. |
| WARNING | Install and enable the SOAP extension.                                                                 |
| WARNING | Install and enable the Tidy extension.                                                                 |
| WARNING | Disable Phar extension to reduce the risk of PHP unserialization vulnerability.                        |
| WARNING | Install and enable the IMAP extension.                                                                 |
| WARNING | Library `jpegoptim` should be installed                                                                |
| WARNING | Library `pngquant` should be installed                                                                 |
+---------+--------------------------------------------------------------------------------------------------------+
The application meets all mandatory requirements
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
  > Oro\Bundle\DigitalAssetBundle\Migrations\Schema\OroDigitalAssetBundleInstaller
    ERROR: The target-entity Oro\Bundle\MagentoBundle\Entity\Customer cannot be found in 'Oro\Bundle\CalendarBundle\Entity\CalendarEvent#customer_11e85188'.
  > Oro\Bundle\ImportExportBundle\Migrations\Schema\v1_1\OroImportExportBundle - skipped
  > Oro\Bundle\ImportExportBundle\Migrations\Schema\v1_2\OroImportExportBundle - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\v1_5\AddEventNameColumn - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\v1_5\DropEventTable - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\v1_6\AddNotificationAlertTable - skipped
  > Oro\Bundle\AddressBundle\Migrations\Schema\v1_5\UpdateObjectClassFieldLength - skipped
  > Oro\Bundle\AddressBundle\Migrations\Schema\v1_6\UpdateLocaleFieldLength - skipped
  > Oro\Bundle\ApiBundle\Migrations\Schema\OroApiBundleInstaller - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_7\ChangeObjectIdColumnPartOne - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_7\ChangeObjectIdColumnPartTwo - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_8\UpdateColumns - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_8\AddUniqIndexForTransactionField - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_8\AddOAuthTypeMigration - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_9\IncreaseTokenLength - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_10\AddUidFieldToFolder - skipped
  > Oro\Bundle\SearchBundle\Migrations\Schema\v1_8\AlterSearchWeightField - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_9\AddSegmentNameValidationColumn - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_10\UpdateLengthSnapshotSegmentIdColumn - skipped
  > Oro\Bundle\CRMBundle\Migrations\Schema\v4_2_0_1\RemoveMagentoOneConnector - skipped
  > Oro\Bundle\CalendarBundle\Migrations\Schema\v1_21\UpdateCalendarEventFields - skipped
  > Oro\Bundle\CalendarBundle\Migrations\Schema\v1_21\UpdateCalendarEventIndexes - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_9\RemoveMalformedUrlsFromNavigationItemsAndHistory - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_9\ChangeUrlsLength - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_9\AddPinbarTabTitle - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_9\UpdatePinbarTabTitle - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_10\ChangeUrlsLength - skipped
  > Oro\Bundle\MarketingListBundle\Migrations\Schema\v1_6_1\AddUnionContactedItemsField - skipped
  > Oro\Bundle\AccountBundle\Migrations\Schema\v1_14_1\UpdateAccountEntityConfig - skipped
  > Oro\Bundle\CallBundle\Migrations\Schema\v1_9\UpdateObjectClassFieldLength - skipped
  > Oro\Bundle\CallBundle\Migrations\Schema\v1_10\UpdateLocaleFieldLength - skipped
  > Oro\Bundle\CaseBundle\Migrations\Schema\v1_11\UpdateObjectClassFieldLength - skipped
  > Oro\Bundle\CaseBundle\Migrations\Schema\v1_12\UpdateLocaleFieldLength - skipped
  > OroCRM\Bundle\ZendeskBundle\Migrations\Schema\v1_4\UpdateObjectClassFieldLength - skipped
  > OroCRM\Bundle\ZendeskBundle\Migrations\Schema\v1_5\UpdateLocaleFieldLength - skipped
  > Oro\Bundle\DotmailerBundle\Migrations\Schema\v1_8\AddSyncAttemptsToAbContactsExport - skipped
  > Oro\Bundle\OAuth2ServerBundle\Migrations\Schema\OroOAuth2ServerBundleInstaller - skipped
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
  > Oro\Bundle\EntitySerializedFieldsBundle\Migration\SerializedDataMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
  > Oro\Bundle\ActivityContactBundle\Migration\ActivityContactMigration - skipped
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration - skipped
  > Oro\Bundle\ScopeBundle\Migration\Schema\AddTriggerToRowHashColumn - skipped

In MigrationExecutor.php line 108:
                                                                               
  [RuntimeException]                                                           
  Failed migrations: Oro\Bundle\DigitalAssetBundle\Migrations\Schema\OroDigit  
  alAssetBundleInstaller.
```

**Expected Result**  
No error `ERROR: The target-entity Oro\Bundle\MagentoBundle\Entity\Customer cannot be found in 'Oro\Bundle\CalendarBundle\Entity\CalendarEvent#customer_11e85188'.` during `Oro\Bundle\DigitalAssetBundle\Migrations\Schema\OroDigitalAssetBundleInstaller` execution

**Details about your environment**
- OroCRM version: 4.2.8
- PHP version: 7.4.27
- Database (MySQL, PostgreSQL) version: 8.0
- [Optional] Server operating system (Windows, Ubuntu, CentOS, RHEL, Fedora, other Linux OS) version and bitness (32-bit, 64-bit) : Debian 11

**Comment by simoncarre** [comment]
I fixed the issue by deleting all the fields in error directly from database. For example: `delete from oro_entity_config_field where field_name = 'customer_11e85188';`

But now I have another issue at the end of the command when running `php bin / console oro: assets: build --env = prod --npm-install`:

```
Installing npm dependencies.
/usr/bin/npm ci --loglevel error
Done.
Building assets.
'/usr/bin/node' './node_modules/webpack/bin/webpack.js' '--hide-modules' '--mode=production' '--env.stats=' '--env.symfony=prod' '--colors'
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/www/app/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

In OroAssetsBuildCommand.php line 257:
                 
  Build failed.  
                 

oro:assets:build [-w|--watch] [--hot] [--key KEY] [--cert CERT] [--cacert CACERT] [--pfx PFX] [--pfxPassphrase PFXPASSPHRASE] [-f|--force-warmup] [-i|--npm-install] [--skip-css] [--skip-js] [--skip-babel] [--skip-sourcemap] [--skip-rtl] [--analyze] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--] <command> [<theme>]
```

**Comment by anyt** [comment]
It seems you don't have the webpack.config.js file in the application root folder, or its content is not up-to-date with the version from official repository. 
Pay attention that it is required to merge all the files in the application level to your project during the upgrade, just bumping up versions in composer.json is not enough.

**Comment by simoncarre** [comment]
Hello @anyt,

Thank you for your answer.
The issue came from my package-lock.json file which was not correct. I deleted it and ran the command again and it fixed my issue.
I am now trying to correct the various issues following the upgrade in my custom code..

```
An exception has been thrown during the rendering of a template ("The "Oro\Bundle\DashboardBundle\Model\WidgetConfigs" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.").
```

I see that I cannot use this service directly in a controller. But I see it still being used in other internal bundles.

**Comment by anyt** [comment]
There are many ways to fix this issue. The easiest one is configuring a service locator using \Symfony\Bundle\FrameworkBundle\Controller\AbstractController::getSubscribedServices. See https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-subscriber
You can find implementation and controller service definition examples in vendor/oro by looking for `public static function getSubscribedServices()`.

**Comment by simoncarre** [comment]
It works better after this update.
Does a document exist on all the modifications to be made to go from 3.1 to 4.2?
I have now some issues to view dashboard (I disabled all the specific modifications related to the dashboard):
![capture_004](https://user-images.githubusercontent.com/1229419/149784763-9f9f7ef7-712a-4aba-bcc2-9e1a03a45279.png)
![capture_005](https://user-images.githubusercontent.com/1229419/149784811-e0b64a9a-d122-451a-a741-071d24fb2833.png)

Thank you for your help @anyt.

**Comment by anyt** [comment]
> Does a document exist on all the modifications to be made to go from 3.1 to 4.2?

Follow the documentation https://doc.oroinc.com/backend/setup/upgrade-to-new-version/.

> 8. Refer to the **UPGRADE.md and CHANGELOG.md files in the application repository** for a list of changes in the code that may affect the upgrade of some customizations.

**Comment by simoncarre** [comment]
Ok, thank you @anyt
I had an issue following the format update in the config of the parameter `routes_to_expose`. It's now fixed.

I have other issues with actions in custom datagrid. For example:

```
acme-opportunities-grid:
        extends: acme-opportunities-grid-base
        actions:
            view:
                type: navigate
                acl_resource: acme_opportunity_view
                label: oro.grid.action.view
                link: view_link
                icon: eye
                rowAction: true
```
If I comment out the `acl_resource` line the system works fine. But if I enable it, I get the following error:

```
php.CRITICAL: Uncaught Error: Argument 4 passed to Oro\Bundle\DataGridBundle\Extension\Action\ActionExtension::getDisabledActions() must be of the type string, null given, called in /var/www/project/vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Action/ActionExtension.php on line 158 {"exception":"[object] (TypeError(code: 0): Argument 4 passed to Oro\\Bundle\\DataGridBundle\\Extension\\Action\\ActionExtension::getDisabledActions() must be of the type string, null given, called in /var/www/project/vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Action/ActionExtension.php on line 158 at /var/www/project/vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Action/ActionExtension.php:351)"} []
```

**Comment by simoncarre** [comment]
Hello @anyt,

It looks like the field level permission **Global** has been removed and replaced by **Organization** :
![capture_001](https://user-images.githubusercontent.com/1229419/150991887-69fa4e9d-4da8-4943-99fd-0312a4d9b0bb.png)

I still see **Global** in the documentation though: https://doc.oroinc.com/user/back-office/system/user-management/roles/. This is an issue on my side or the field has disappeared? (I have entities that are not linked to an organization: only an owner).

Thank you in advance.

**Comment by anyt** [comment]
> I have entities that are not linked to an organization: only an owner

If these entities have an ownership type equal to user or business unit - they must have an organization assigned as well.

> This is an issue on my side or the field has disappeared? 

As I see in a clean instance - nothing changed out of the box, so this is probably on the customization side.

**Comment by anyt** [comment]
Also, this might be a translation issue for the French localization. As in the community edition, organization and global level mean the same

**Comment by simoncarre** [comment]
Hello @anyt,

> If these entities have an ownership type equal to user or business unit - they must have an organization assigned as well.

On our custom entities, in version 3.1, we operated without a linked organization (only `owner_field_name` and `owner_column_name`). Here is the configuration on our custom entity:

```
 * @Config(
 *     defaultValues={
 *         "dataaudit"={
 *              "auditable"=true
 *         },
 *         "ownership"={
 *              "owner_type"="USER",
 *              "owner_field_name"="dynamicOwner",
 *              "owner_column_name"="dynamic_owner_id"
 *          },
 *         "security"={
 *              "type"="ACL",
 *              "group_name"=""
 *         },
 *     }
 * )
```

But according to the current doc, the fields on the organization are now mandatory:
![capture_002](https://user-images.githubusercontent.com/1229419/151331638-2394a7ef-95a5-4454-9210-3426de235ecb.png)

I think the issue comes from here...
I also saw that the `Global` level was only available in the enterprise version:
![capture_001](https://user-images.githubusercontent.com/1229419/151331981-83ae09b9-3197-4e6d-982d-716b8f586981.png)

https://doc.oroinc.com/backend/security/acl/
