### ISSUE TITLE
Argument #1 ($name) must be of type string, null given when using dropdowns in CRM

### ISSUE THREAD

**Issue by makeitaboldmove** [oroinc/crm#372]
**Summary**  
 ````
request.CRITICAL: Uncaught PHP Exception TypeError: "Oro\Bundle\FormBundle\Autocomplete\Security::isAutocompleteGranted(): Argument #1 ($name) must be of type string, null given, called in /var/www/html/vendor/oro/platform/src/Oro/Bundle/FormBundle/Controller/AutocompleteController.php on line 52" at /var/www/html/vendor/oro/platform/src/Oro/Bundle/FormBundle/Autocomplete/Security.php line 29 {"exception":"[object] (TypeError(code: 0): Oro\\Bundle\\FormBundle\\Autocomplete\\Security::isAutocompleteGranted(): Argument #1 ($name) must be of type string, null given, called in /var/www/html/vendor/oro/platform/src/Oro/Bundle/FormBundle/Controller/AutocompleteController.php on line 52 at /var/www/html/vendor/oro/platform/src/Oro/Bundle/FormBundle/Autocomplete/Security.php:29)"}
````

**Steps to reproduce**  
Try using any dropdown within the CRM.

**Actual Result**
This PHP error.

**Expected Result**  
Not a PHP error.

**Details about your environment**
- OroCRM version: 5.0.8
- PHP version: 8.1.14
- Database (MySQL, PostgreSQL) version:  10.6.11-MariaDB

**Comment by mbessolov** [comment]
@makeitaboldmove Sorry, but this is not enough to reproduce the problem. On a vanilla installation of OroCRM all drop-down with autocomplete work fine for me.

Please enable web developer dev tools in your browser, and copy the URL of the request that is being sent to the server when you open a drop-down. It would look similar to https://demo.orocrm.com/index.php/activities/emails/search/autocomplete?name=emails&page=1&per_page=10&query=&_=1675815387763 , and may vary based on which specific drop-down you open.

A screenshot of the page will be helpful as well.

**Comment by makeitaboldmove** [comment]
Request URL: https://test.upullandsave.com/autocomplete/search?params%5Bpermission%5D=ASSIGN&params%5Bentity%5D=Oro_Bundle_AccountBundle_Entity_Account&params%5Bentity_id%5D=1&page=1&per_page=10&name=acl_users&query=%3BOro_Bundle_AccountBundle_Entity_Account%3BASSIGN%3B1%3B&_=1675864933409

Screenshots of an Edit Account page and the above request URL: https://imgur.com/a/S2EuORT

**Comment by makeitaboldmove** [comment]
I was able to fix this by updating part of my nginx server block.

````					
location / {
	try_files $uri $uri/ /index.php$is_args$args;
}
location ~ \.php$ {
	include snippets/fastcgi-php.conf;
	fastcgi_read_timeout 300;
	fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
````

to

````
location / {
    try_files $uri /index.php$is_args$args;
}
location ~ ^/(index|index_dev|config|install)\.php(/|$) {
	include snippets/fastcgi-php.conf;
	fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
	fastcgi_split_path_info ^(.+\.php)(/.*)$;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
````

Seems my config file somehow lost the `fastcgi_split_path_info` line...

Thanks again! Sorry for the trouble.
