### ISSUE TITLE
OroCRM license is incompatible with the wider open source ecosystem

### ISSUE THREAD

**Issue by SimonBiggs** [oroinc/crm#374]
Hi,

I was hoping to be able to build on top of OroCRM a range of open source AI based tooling / plugins. But I noticed that the license you have chosen for this project is incompatible with the GPL:

https://www.gnu.org/licenses/license-list.en.html#OSL

This makes it so that I cannot do the above while utilising the range of open source tools within my toolbox. No matter how amazing the software is, I choose open source tools within my stack so that I am free to be able to build on top of them. As such, for now, due to OroCRM's incompatibility, it is disqualified from selection.

Is it too late for this project to be able to change to a license that is compatible with the wider open source ecosystem? (such as a GPL/AGPL, Apache, or MIT license?)

Cheers,
Simon

**Comment by mbessolov** [comment]
Hi Simon,

OSL is an open-source license, and it should not prevent you from building open source tools on top of that.
OSL has actually a lot more focus on the "open source" part than other licenses you mentioned, as it makes much greater emphasis on making the source code of your modifications published as open-source code compared to other open source licenses.

And if you ever decide to convert your tools/plugins into a closed-source commercial product, then feel free to reach to our sales team as an OroCRM enterprise license is available as well (at a price).

Thank you,
Michael

**Comment by SimonBiggs** [comment]
> OSL has actually a lot more focus on the "open source" part than other licenses you mentioned, as it makes much greater emphasis on making the source code of your modifications published as open-source code compared to other open source licenses.

It makes a greater emphasis on modifications being published as open source than the GPL or the AGPL? That's interesting. I'd be keen to know more about that.

> OSL is an open-source license, and it should not prevent you from building open source tools on top of that.

Does that mean that the GNU license documentation that I linked above is wrong in this case? I copied it below for reference:

> The Open Software License is a free software license. It is incompatible with the GNU GPL in several ways.
> 
> Recent versions of the Open Software License have a term which requires distributors to try to obtain explicit assent to the license. This means that distributing OSL software on ordinary FTP sites, sending patches to ordinary mailing lists, or storing the software in an ordinary version control system, is arguably a violation of the license and would subject you to possible termination of the license. Thus, the Open Software License makes it very difficult to develop software using the ordinary tools of free software development. For this reason, and because it is incompatible with the GPL, **we recommend that no version of the OSL be used for any software.**
> 
> **We urge you not to use the Open Software License for software you write.** However, there is no reason to avoid running programs that have been released under this license.

https://www.gnu.org/licenses/license-list.en.html#OSL

**Comment by mbessolov** [comment]
You can read more detailed explanation of the OSL license from the author here - https://rosenlaw.com/OSL3.0-explained.htm

**Comment by SimonBiggs** [comment]
Thanks for your information and your time. I wish you well :slightly_smiling_face:.

Cheers,
Simon
