### ISSUE TITLE
Out of memory on install 

### ISSUE THREAD

**Issue by james2001** [oroinc/crm#377]
**Summary**  
During the installation of OroCRM on a Docker environment with PHP 8.3, the installation fails due to a memory exhaustion error, even after setting an extended memory limit.

**Steps to reproduce**  
1. Use a Docker image based on PHP 8.3 with the required extensions for OroCRM.
2. Run the following installation command:
   ```bash
   bin/console oro:install --timeout=2000 --env=prod
   ```
3. The installation fails after the "Process migrations" step, with memory usage increasing to about 11 GB before the process is killed.

**Actual Result**  
The installation fails with the following error:

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 40960 bytes) in /var/www/website/vendor/symfony/dependency-injection/Container.php on line 290

In Container.php line 290:

  Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 40960 bytes)
```

Despite setting `memory_limit = -1`, the process gets killed after consuming approximately 11 GB of memory.

 ```bash
The application meets all mandatory requirements
Setting up database.
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
    66.50 MiB - 134 ms
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
    68.50 MiB - 78 ms
  > Oro\Bundle\NoteBundle\Migration\RemoveNoteConfigurationScopeMigration
    68.50 MiB - 663 ms
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration
    70.50 MiB - 1513 ms
The process has been signaled with signal "9".
 ```

**Expected Result**  
The installation should complete successfully without memory exhaustion, or at least manage memory usage more appropriately (instead of exceeding 11 GB).

**Details about your environment**
- **OroCRM version**: 6.0.*
- **PHP version**: 8.3.12
- **Database**: PostgreSQL 
- **Server operating system**: Docker
- **Installed extensions**: intl, opcache, pdo_mysql, pdo_pgsql, soap, gd, zip, mbstring, curl, bcmath, ldap, xml, dom, mongodb, pcntl, tidy, imap
- **Web-server**: nginx
- **Client operating system**: WSL2
- **Client browser**: Not relevant for this bug
- **Composer.json**: Includes dependencies for `"oro/crm": "6.0.*"` and other standard OroCRM packages.

**Additional information**  
This issue occurs during a fresh installation with the following `composer.json` snippet:
```json
"require": {
    "php": "~8.3.0",
    "oro/crm": "6.0.*",
    "oro/platform-serialised-fields": "6.0.*",
    "oro/oauth2-server": "6.0.*",
    "oro/crm-dotmailer": "6.0.*",
    "oro/crm-zendesk": "6.0.*"
},
```

The Docker container is configured to use a memory limit of `1024M`, but even with `memory_limit = -1`, the installation fails after consuming 11 GB of memory. Logs do not provide clear indications as to the exact cause of the excessive memory usage.

---

```
FROM php:8.3-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && sync

RUN apt-get update && apt-get install -y wget \
    zlib1g-dev g++ git libicu-dev zip libzip-dev unzip libpq-dev jpegoptim pngquant tidy

RUN install-php-extensions \
    intl \
    opcache \
    pdo_mysql \
    pdo_pgsql \
    soap \
    gd \
    zip \
    mbstring \
    curl \
    bcmath \
    ldap \
    xml \
    dom \
    mongodb \
    pcntl \
    tidy \
    imap

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN wget https://get.symfony.com/cli/installer -O - | bash && \
    mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

WORKDIR /var/www/website

# install npm

ENV NODE_VERSION=20.18.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

# Disable Phar
RUN echo "phar.readonly = On" > /usr/local/etc/php/conf.d/phar.ini

# Set short_open_tag to off
RUN echo "short_open_tag = Off" > /usr/local/etc/php/conf.d/short_open_tag.ini

# Set memory_limit to 1024M
RUN echo "memory_limit = 1024M" > /usr/local/etc/php/conf.d/memory_limit.ini
```

**Comment by mbessolov** [comment]
Hello @james2001 

Thank you for the detailed report.

Can you point to a specific problem in Oro application itself?

Retracing this custom Docker image build steps and debugging what docker-php-extension-installer does is not really what we usually do.

You can setup OroCRM using our own recommended Docker setup with docker-compose - https://github.com/oroinc/docker-demo , or you can try to build your custom all-in-one image using https://hub.docker.com/r/oroinc/orocommerce-application as a starting point if you strongly prefer single-image setups. 

Feel free to report a new issue if you run into problems with any of our Docker images.

Thank you

**Comment by mbessolov** [comment]
Might be caused by changes in symfony/dependency-injection 6.4.12 -  https://github.com/oroinc/platform/issues/1116
As a workaround, try to explicitly lock the version of symfony/dependency-injection in composer.json of your application.
