### ISSUE TITLE
when i run docker compose up for demo,I got this error

### ISSUE THREAD

**Issue by Steps-devmyself** [oroinc/crm#378]
**Summary**  

sed: couldn't open temporary file /var/www/oro_app/config/sedBi02jP: Permission denied
![image](https://github.com/user-attachments/assets/d83a0af1-0c0d-4c9b-812a-d263fd2a1cc9)

**Steps to reproduce**  

**Actual Result**

**Expected Result**  

**Details about your environment**
- OroCRM version: x.y.z
- PHP version: x.y.z
- Database (MySQL, PostgreSQL) version

**Additional information**

**Comment by mbessolov** [comment]
It's not clear what docker images are being used here.
Please make sure to provide all details when reporting a problem like this. Do not leave the template sections empty - they are here to be filled.
